PrototypeApp({
  name:'协作方舟 OA',en:'COLLABORATIVE OFFICE',color:'#2563eb',color2:'#06b6d4',user:'陈予安',role:'部门负责人',badge:14,
  greeting:'上午好，陈予安',subtitle:'你有 8 项待办，其中 2 项将在今天超时。',entity:'审批',metricLabel:'流程时效',
  nav:['企业门户','统一待办','流程中心','公文管理','会议日程','行政服务','组织通讯录','数据看板','系统管理'],
  kpis:[{label:'待我处理',value:'8',trend:'2 项紧急'},{label:'今日会议',value:'4',trend:'下场 10:30'},{label:'本月办结',value:'126',trend:'↑ 15.4%'},{label:'审批及时率',value:'92.6%',trend:'↑ 3.2%'}],
  chartTitle:'流程发起与办结趋势',donutTitle:'待办类型分布',focusTitle:'待我处理',categories:['费用报销','采购申请','人事流程'],
  rows:[{name:'华东区客户拜访费用报销',code:'BX-20260707-0031',status:'待部门审批',value:'剩余 2 小时',progress:76,owner:'林知夏'},{name:'研发中心测试设备采购',code:'CG-20260707-0018',status:'待负责人审批',value:'剩余 5 小时',progress:64,owner:'宋嘉禾'},{name:'市场部 7 月活动用印',code:'YZ-20260706-0012',status:'即将超时',value:'剩余 45 分',progress:92,owner:'周景行'},{name:'设计中心年假申请',code:'QJ-20260706-0026',status:'待部门审批',value:'剩余 8 小时',progress:48,owner:'许清和'},{name:'季度经营会会议室申请',code:'HY-20260705-0009',status:'待行政确认',value:'剩余 1 天',progress:34,owner:'沈听澜'}],
  activities:['林知夏发起华东区费用报销','总经办发布「第三季度经营会议通知」','宋嘉禾提交测试设备采购申请','会议室「云海」预订时间发生冲突','公文 GW-2026-0046 已完成并行会签'],
  pages:{
    1:{entity:'待办审批',description:'统一处理待办、已办、我发起和抄送流程，支持催办、退回和转交。',metricLabel:'剩余时限',ownerLabel:'发起人',primaryAction:'发起审批',codePrefix:'FLOW',initialStatus:'审批中',activeStatus:'下一节点',reviewStatus:'即将办结',advanceAction:'同意并流转',categories:['费用报销','请假申请','采购申请'],rows:[{name:'华东区客户拜访费用报销',code:'BX-20260707-0031',status:'待部门审批',value:'剩余 2 小时',progress:76,owner:'林知夏'},{name:'研发中心测试设备采购',code:'CG-20260707-0018',status:'待负责人审批',value:'剩余 5 小时',progress:64,owner:'宋嘉禾'},{name:'市场部 7 月活动用印',code:'YZ-20260706-0012',status:'即将超时',value:'剩余 45 分',progress:92,owner:'周景行'}]},
    2:{kind:'kanban',entity:'流程模板',description:'按业务分类发起流程，并由管理员配置表单、条件分支、处理人和 SLA。',metricLabel:'流程版本',ownerLabel:'流程管理员',primaryAction:'新建流程模板',codePrefix:'TPL',initialStatus:'草稿',activeStatus:'配置中',reviewStatus:'已发布',advanceAction:'发布流程版本',categories:['人事流程','财务流程','行政流程'],kanban:['草稿','配置与测试','已发布'],rows:[{name:'费用报销审批',code:'TPL-FIN-008',status:'已发布',value:'V3.2',progress:92,owner:'流程管理员'},{name:'员工请假审批',code:'TPL-HR-003',status:'运行中',value:'V2.6',progress:86,owner:'人力运营'},{name:'采购申请审批',code:'TPL-PUR-012',status:'测试中',value:'V1.8',progress:68,owner:'采购运营'}]},
    3:{kind:'kanban',entity:'公文',description:'支持拟稿、核稿、并行会签、签发、编号、发布和归档。',metricLabel:'文号/密级',ownerLabel:'拟稿部门',primaryAction:'公文拟稿',codePrefix:'GW',initialStatus:'草稿',activeStatus:'会签中',reviewStatus:'待签发',advanceAction:'推进公文流转',categories:['通知','决定','请示'],kanban:['拟稿与核稿','会签','签发与归档'],rows:[{name:'关于第三季度经营会议的通知',code:'GW-2026-0046',status:'会签中',value:'普通 · 拟46号',progress:72,owner:'总经办'},{name:'研发中心设备采购批复',code:'GW-2026-0042',status:'待签发',value:'内部 · 批18号',progress:88,owner:'总经办'},{name:'信息安全管理制度修订',code:'GW-2026-0038',status:'核稿中',value:'内部 · 制12号',progress:54,owner:'信息中心'}]},
    4:{kind:'calendar',entity:'会议日程',description:'查看个人与团队日程，创建会议、预订会议室并管理行动项。',metricLabel:'会议时间',ownerLabel:'组织者',primaryAction:'新建会议',codePrefix:'MEET',initialStatus:'待确认',activeStatus:'已安排',advanceAction:'完成会议',categories:['经营会议','项目会议','客户会议'],rows:[{name:'第三季度经营分析会',code:'MEET-260708-018',status:'已确认',value:'今天 10:30',progress:80,owner:'陈予安'},{name:'CRM 项目周例会',code:'MEET-260709-011',status:'待参会确认',value:'明天 14:00',progress:46,owner:'宋嘉禾'},{name:'信息安全制度评审',code:'MEET-260710-006',status:'会议室已锁定',value:'周五 09:30',progress:62,owner:'周景行'}]},
    5:{entity:'行政申请',description:'集中办理会议室、用车、办公用品、用印和访客等行政服务。',metricLabel:'资源/数量',ownerLabel:'申请人',primaryAction:'发起行政申请',codePrefix:'ADM',initialStatus:'待审批',activeStatus:'办理中',reviewStatus:'待确认',advanceAction:'确认行政办理',categories:['会议室','用车','办公用品'],rows:[{name:'云海会议室预订',code:'ROOM-260708-025',status:'已通过',value:'20 人 / 2小时',progress:90,owner:'林知夏'},{name:'机场客户接待用车',code:'CAR-260709-012',status:'车辆已分配',value:'7 座商务车',progress:72,owner:'宋嘉禾'},{name:'设计中心办公用品领用',code:'SUPPLY-260708-037',status:'待领取',value:'12 件',progress:68,owner:'许清和'}]},
    6:{entity:'组织人员',description:'通过组织树查询部门、岗位、联系方式、在岗状态和汇报关系。',metricLabel:'岗位',ownerLabel:'所属部门',primaryAction:'新增人员',codePrefix:'EMP',initialStatus:'待入职',activeStatus:'在职',advanceAction:'更新人员状态',categories:['正式员工','外包人员','实习生'],rows:[{name:'林知夏',code:'EMP-001286',status:'在职',value:'高级销售经理',progress:100,owner:'销售中心'},{name:'宋嘉禾',code:'EMP-001251',status:'在职',value:'产品经理',progress:100,owner:'产品中心'},{name:'许清和',code:'EMP-001209',status:'休假中',value:'行政主管',progress:88,owner:'行政中心'}]},
    7:{kind:'analytics',entity:'OA 指标',description:'分析流程量、办结时长、超时率、部门效率和活跃用户。',metricLabel:'指标值',ownerLabel:'统计周期',chartTitle:'流程发起与办结趋势',donutTitle:'流程类型构成',categories:['财务流程','人事流程','行政流程'],kpis:[{label:'本月发起量',value:'1,286',trend:'↑ 15.4%'},{label:'平均办结时长',value:'6.8小时',trend:'↓ 1.2小时'},{label:'审批及时率',value:'92.6%',trend:'↑ 3.2%'},{label:'活跃用户',value:'86.4%',trend:'↑ 4.8%'}],rows:[{name:'审批及时率',code:'KPI-SLA',status:'达标',value:'92.6%',progress:93,owner:'本月'},{name:'流程平均办结时长',code:'KPI-CYCLE',status:'持续改善',value:'6.8 小时',progress:84,owner:'本月'},{name:'待办超时率',code:'KPI-OVERDUE',status:'需关注',value:'7.4%',progress:74,owner:'本周'}]},
    8:{kind:'settings',entity:'OA 配置',description:'管理组织、角色、应用菜单、流程模板、数据字典和审计日志。',metricLabel:'当前配置',ownerLabel:'维护人',categories:['组织权限','流程','应用'],rows:[{name:'组织架构与用户',code:'SET-ORG',status:'已同步',value:'5 个部门 / 35 人',progress:100,owner:'系统管理员'},{name:'角色与数据权限',code:'SET-RBAC',status:'已启用',value:'4 个角色',progress:100,owner:'系统管理员'},{name:'流程 SLA 与工作日历',code:'SET-SLA',status:'待完善',value:'8 个流程模板',progress:72,owner:'流程管理员'},{name:'应用菜单与门户布局',code:'SET-APP',status:'已发布',value:'9 个应用',progress:100,owner:'系统管理员'}]}
  },
  roles:[{name:'部门负责人',user:'陈予安',scope:'本部门数据',nav:[0,1,2,3,4,5,6,7],permissions:['create','edit','export','advance']},{name:'普通员工',user:'林知夏',scope:'个人数据',nav:[0,1,2,4,5,6],permissions:['create','edit']},{name:'行政专员',user:'许清和',scope:'全部数据',nav:[0,1,2,3,4,5,6,7],permissions:['create','edit','export','advance']},{name:'系统管理员',user:'唐知微',scope:'全部数据',nav:[0,1,2,3,4,5,6,7,8],permissions:['export']}]
});
